#
# Makefile for the Novatek NT11207 touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT11207)	+= NVTtouch_207.o NVTtouch_207_ext_proc.o NVTtouch_207_fw_update.o NVTtouch_207_mp_ctrlram.o
